[package]
name = "oct_normal"
version = "0.1.0"
edition = "2021"

[features]
half = ["dep:half"]

[dependencies]
half = { version = "2.4.1", optional = true }

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
